# Site settings
title: Blog Herman
description: 'Business Card Page'
url: 'http://h_granzow_c'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Herman Granzow'
  email: hfgranzow@gmail.com
#  twitter_username: 
#  facebook_username: joshgerdes
  github_username:  HFGC-82
  linkedin_username:  herman-granzow-msc-caia-1291ba33/
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
